export const RE_ERROR_CODES = {
  // Stage 0
  CONTRACT_VERSION_ERROR: 'CONTRACT_VERSION_ERROR',

  // Stage 1 — Schema
  SCHEMA_VALIDATION_ERROR: 'SCHEMA_VALIDATION_ERROR',
  PARAMETER_MISSING_REQUIRED: 'PARAMETER_MISSING_REQUIRED',
  PARAMETER_MISSING_CONDITIONAL: 'PARAMETER_MISSING_CONDITIONAL',
  PARAMETER_TYPE_MISMATCH: 'PARAMETER_TYPE_MISMATCH',
  PARAMETER_UNKNOWN: 'PARAMETER_UNKNOWN',

  // Stage 2 — Range
  PARAMETER_OUT_OF_RANGE: 'PARAMETER_OUT_OF_RANGE',
  DATA_QUALITY_WARNING: 'DATA_QUALITY_WARNING',
  HURDLE_RATE_DEVIATION: 'HURDLE_RATE_DEVIATION',
  TAX_RATE_DEVIATION: 'TAX_RATE_DEVIATION',
  IRR_SIGN_INCONSISTENCY: 'IRR_SIGN_INCONSISTENCY',

  // Stage 3 — Conditional
  CONDITIONAL_PARAMETER_MISSING: 'CONDITIONAL_PARAMETER_MISSING',
  CONDITIONAL_EVIDENCE_MISSING: 'CONDITIONAL_EVIDENCE_MISSING',

  // Stage 4 — Consistency
  DATA_CONSISTENCY_WARNING: 'DATA_CONSISTENCY_WARNING',
  AREA_SUM_INCONSISTENCY: 'AREA_SUM_INCONSISTENCY',
  MIX_PCT_SUM_INCONSISTENCY: 'MIX_PCT_SUM_INCONSISTENCY',
  NPV_NET_PROFIT_INCONSISTENCY: 'NPV_NET_PROFIT_INCONSISTENCY',
  ROI_CONSISTENCY_WARNING: 'ROI_CONSISTENCY_WARNING',
  SCENARIO_ORDER_VIOLATION: 'SCENARIO_ORDER_VIOLATION',
  MIRR_IRR_VIOLATION: 'MIRR_IRR_VIOLATION',
  CAPITAL_STRUCTURE_INCONSISTENCY: 'CAPITAL_STRUCTURE_INCONSISTENCY',
  AREA_BUILD_RATIO_VIOLATION: 'AREA_BUILD_RATIO_VIOLATION',

  // Stage 5 — Evidence
  EVIDENCE_MISSING_CRITICAL: 'EVIDENCE_MISSING_CRITICAL',
  EVIDENCE_MISSING_REQUIRED: 'EVIDENCE_MISSING_REQUIRED',
  EVIDENCE_MISSING_ADVISORY: 'EVIDENCE_MISSING_ADVISORY',
  EVIDENCE_FRESHNESS_WARNING: 'EVIDENCE_FRESHNESS_WARNING',

  // Stage 7 — Rule Results
  RULE_CRITICAL_BLOCK: 'RULE_CRITICAL_BLOCK',
  RULE_ADVISORY_WARN: 'RULE_ADVISORY_WARN',
} as const

export type REErrorCode = (typeof RE_ERROR_CODES)[keyof typeof RE_ERROR_CODES]
